services:
  app:
    build: .
    ports:
      - '${PORT}:${PORT}' # 8080:8080
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432' # 5433 (host) -> 5432 (container)
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
